### ISSUE TITLE
"project/" directory is missing

### ISSUE THREAD

**Issue by fourcube** [alvinj/SbtSubProjectsExample#1]
The "project/" directory is missing because it is excluded in the .gitignore file.

It's not too bad if one owns your book, but it would be great if the "project/Build.scala" file could be found here as well.

**Comment by alvinj** [comment]
Sorry about that. This has been corrected. Thanks for letting me know about
the problem.

On Tue, Sep 24, 2013 at 8:51 AM, fourcube notifications@github.com wrote:

> The "project/" directory is missing because it is excluded in the
> .gitignore file.
> 
> It's not too bad if one owns your book, but it would be great if the
> "project/Build.scala" file could be found here as well.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/alvinj/SbtSubProjectsExample/issues/1
> .

## 

alvin alexander
http://www.devdaily.com
